name: Python Schedule Script

on:
  schedule:
  - cron: '0 0 31 12 *' #at 00:00 on December 31st
  workflow_dispatch: # Allows to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content 
      uses: actions/checkout@v4 #Checkout the repository content to github reunner


    - name: Setup Python Version 
      uses: actions/setup-python@v5
      with: 
        python-version: '3.12' #install the python  version


    - name: install python packages 
      run:  | 
            python -m pip install --upgrade pip 
            pip install -r requirements.txt

    - name: Execute Python Script
      run: | 
        TZ=America/New_York python NoaaToDrive_V2.py 
        
      
